---

# This playbook tries to download configuration and log files related to RHSC
# 2.0 only instead of just downloading everything. This can be also useful when
# one needs to tweak the list further - copy this into new playbook and just
# comment out or add directories or files as you like.

- name: Download evidence available on all machines
  hosts: all
  user: root
  vars:
    evidence_dirs:
     - /var/log/audit/
     - /var/log/salt/
     - /etc/yum.repos.d/
    evidence_files:
     - /var/log/messages
     - /proc/cpuinfo
     - /proc/meminfo
  roles:
    - qe-evidence
    - qe-evidence-probe

- name: Download evidence from RHSC 2.0 machine
  hosts: tendrl-server
  user: root
  vars:
    evidence_dirs:
     - /etc/carbon/
     - /etc/ceph-installer/
     - /etc/graphite-web/
     - /etc/rabbitmq/
     - /etc/skyring/
     - /var/log/carbon/
     - /var/log/graphite-web/
     - /var/log/httpd/
     - /var/log/mongodb/
     - /var/log/rabbitmq/
     - /var/log/skyring/
  roles:
    - role: qe-evidence

- name: Download logs from Ceph Storage machines
  hosts: usm_nodes
  user: root
  vars:
    evidence_dirs:
     - /etc/ceph/
     - /etc/skynet
     - /var/log/ceph/
     - /var/log/skynet/
  roles:
   - role: qe-evidence

- name: Download logs from Ceph Monitor machines
  hosts: ceph_mon
  user: root
  vars:
    evidence_dirs:
     - /etc/calamari/
     - /var/log/calamari/
  roles:
   - role: qe-evidence
