---

# This playbook tries to download configuration and log files related to Tendrl
# only instead of just downloading everything. This can be also useful when
# one needs to tweak the list further - copy this into new playbook and just
# comment out or add directories or files as you like.

- name: Download evidence available on all machines
  hosts: all
  user: root
  vars:
    evidence_dirs:
      - /var/log/audit/
      - /etc/yum.repos.d/
    evidence_files:
      - /var/log/messages
      - /var/log/yum.log
      - /var/log/boot.log
      - /proc/cpuinfo
      - /proc/meminfo
      - /proc/cmdline
      - /proc/version
      - /proc/devices
      - /proc/partitions
      - /etc/hosts
      - /etc/os-release
      - /etc/machine-id
  roles:
    - qe-evidence
    - qe-evidence-probe

- name: Download evidence from Tendrl server machine
  hosts: tendrl-server
  user: root
  vars:
    evidence_dirs:
      - /etc/httpd/
      - /etc/etcd/
      - /etc/carbon/
      - /etc/graphite-web/
      - /etc/ceph-installer/
      - /etc/grafana/
      - /etc/collectd_template/
      - /etc/collectd.d/
      - /etc/tendrl/
      - /var/log/tendrl/
      - /var/log/httpd/
      - /var/log/carbon/
      - /var/log/graphite-web/
      - /var/log/grafana/
    evidence_files:
      - /etc/collectd.conf
    evidence_journald_services:
      - tendrl-api
      - tendrl-node-agent
      - tendrl-monitoring-integration
      - tendrl-notifier
  roles:
    - qe-evidence
    - qe-evidence-probe-journald

- name: Download logs from Storage machines
  hosts: usm_nodes
  user: root
  vars:
    evidence_dirs:
      - /etc/collectd_template/
      - /etc/collectd.d/
      - /etc/tendrl/
      - /var/log/tendrl/
    evidence_files:
      - /etc/collectd.conf
    evidence_journald_services:
      - tendrl-node-agent
  roles:
    - role: qe-evidence
    - qe-evidence-probe-journald

- name: Download logs from Gluster Storage machines
  hosts: gluster
  user: root
  vars:
    evidence_dirs:
      - /etc/glusterfs/
      - /var/log/glusterfs/
    evidence_journald_services:
      - tendrl-gluster-integration
  roles:
    - qe-evidence
    - qe-evidence-probe-journald

- name: Download logs from Ceph Storage machines
  hosts: ceph_osd ceph_mon
  user: root
  vars:
    evidence_dirs:
      - /etc/ceph/
      - /var/log/ceph
    evidence_journald_services:
      - tendrl-ceph-integration
  roles:
   - role: qe-evidence
   - qe-evidence-probe-journald
