---
#
# Install useful and auxiliary tools
#
- hosts: tendrl-server:gluster-servers:usm_client
  remote_user: root
  tasks:
    - name: Install useful tools
      yum: name={{ item }} state=installed
      with_items:
        - bash-completion
        - bind-utils
        - git
        - psmisc
        - screen
        - tmux
        - tree
        - vim
        - lsof
      register: task_result
      until: task_result|success
      retries: 5
      delay: 5
      ignore_errors: yes
