---
# This just starts/stops all skyring services across the cluster.
# Created to help with SELinux policy development.
#
# Usage:
# ansible-playbook -i usm2.hosts --extra-vars service_state=started services.skyrings.yml

- name: Start/Stop all services on Skyrings server
  hosts: "tendrl-server"
  remote_user: root

  tasks:

    - name: Start/Stop Skyring
      service: name=skyring state={{ service_state }}

    - name: Start/Stop other services
      service: name={{ item }} state={{ service_state }}
      with_items:
        - salt-master
        - ceph-installer
        - ceph-installer-celery
        - carbon-cache
        - httpd
        - rabbitmq-server
        - mongod
        - libstoragemgmt

- name: Start/Stop all services on all Ceph Storage Nodes (MONs and OSDs)
  hosts: "ceph_osd:ceph_mon"
  remote_user: root

  tasks:

    - name: Start/Stop Skynet
      service: name=skynetd state={{ service_state }}

    - name: Start/Stop all other services
      service: name={{ item }} state={{ service_state }}
      with_items:
        - salt-minion
        - collectd
        - salt-minion
        - storaged
        - libstoragemgmt
